bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

benni_rugs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('services/', include('services.urls')),
    path('testimonials/', include('testimonials.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml/', sitemap, {"sitemaps": sitemap}, name="django.contrib.sitemaps.views.sitemap",),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ContactUs.as_view(), name='contact'),
    path('enquiries/', views.Enquiries.as_view(), name='enquiries'),
    path('enquiries/<int:pk>/',views.EnquiryDetail.as_view(), name='enquiry_detail'),
    path('enquiries/delete/<int:pk>/', views.DeleteEnquiry.as_view(), name='delete_enquiry'),
]

contact/models.py
""" Contact Models """

from django.db import models
from django.urls import reverse


class Contact(models.Model):
    """ Model for Contact """

    DESIGN_CONSULTATION = 'DS'
    PRODUCT_QUERY = 'PQ'
    ORDER_QUERY = 'OQ'
    DELIVERY_QUERY = 'DR'
    DELIVERY_INSURANCE = 'DI'
    RUG_REPAIR = 'RR'
    RUG_WASHING = 'RW'
    OTHER = 'O'
    ENQUIRY_CHOICES = [
        ('DESIGN_CONSULTATION', 'Rug Design Consultation'),
        ('PRODUCT_QUERY', 'Product Query'),
        ('ORDER_QUERY', 'Order Query'),
        ('DELIVERY_QUERY', 'Delivery Query'),
        ('DELIVERY_INSURANCE', 'Delivery and Insurance'),
        ('RUG_REPAIR', 'Rug Repair Services'),
        ('RUG_WASHING', 'Rug Washing Services'),
        ('OTHER', 'Other')
        ]

    name = models.CharField(max_length=122, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    enquiry_type = models.CharField(
        max_length=254, choices=ENQUIRY_CHOICES, default='DS')
    message = models.TextField(max_length=500, default='')
    date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        """Get url after user submits enquiry """
        return reverse('home')

    class Meta:
        """ To display the equiries by date in ascending order """
        ordering = ['-date']

    def __str__(self):
        return f"Enquiry: {self.enquiry_type} from {self.name}"

contact/forms.py
""" Contact forms """

from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'enquiry_type', 'message',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-gold bg-transparent text-gold'

        

contact/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.views import generic, View
from django.conf import settings
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from .forms import ContactForm
from .models import Contact


class ContactUs(View):
    """
    This view is used to display the contact form and
    handle GET and POST requests
    """

    def get(self, request):
        """
        Renders the contact form
        """
        if request.user.is_authenticated:
            form = ContactForm(initial={'email': request.user.email})
        else:
            form = ContactForm()

        return render(
            request,
            "contact/contact.html",
            {
                "contact_form": form,
            },
        )

    def post(self, request):
        """
        This method is called when a POST request is made to the view
        via the contact form
        """
        contact_form = ContactForm(data=request.POST)

        if contact_form.is_valid():
            cust_name = contact_form.instance.name
            cust_email = contact_form.instance.email
            subject = contact_form.instance.enquiry_type
            subject = render_to_string(
                'contact/confirmation_emails/confirmation_email_subject.txt',
                {'subject': subject})
            message = contact_form.instance.message
            message = render_to_string(
                'contact/confirmation_emails/confirmation_email_body.txt',
                {'cust_name': cust_name, 'message': message}
            )
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [cust_email]
            )

            contact_form.save()
            messages.success(self.request, 'Your enquiry has been sent')

            target = "home/index.html"
            context = {"plain_message": True}

        else:
            messages.error(request, """Form failed. Please ensure the
            form is valid """)

            target = "contact/contact.html"
            context = {
                "plain_message": True,
                "contact_form": contact_form
                }

        return render(request, target, context)


class Enquiries(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    """ This view is used to display all enquiries """
    model = Contact
    template_name = 'contact/enquiries_dashboard.html'

    def test_func(self):
        """
        ensures only superuser can view enquiries
        """
        if self.request.user.is_superuser:
            return True

    def get_context_data(self, **kwargs):
        """
        ensures success message doesn't include bag items
        """
        context = super().get_context_data(**kwargs)
        context['plain_message'] = True
        return context


class EnquiryDetail(
        LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    """ This view is used to display selected enquiry detail """
    model = Contact
    template_name = 'contact/enquiry_detail.html'

    def test_func(self):
        """
        ensures only superuser can add view enquiries
        """
        if self.request.user.is_superuser:
            return True


class DeleteEnquiry(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    """
    This view is used to allow the superuser to delete an enquiry
    """
    model = Contact
    template_name = 'contact/delete_enquiry.html'
    success_message = "Enquiry deleted successfully"
    success_url = reverse_lazy('enquiries')

    def test_func(self):
        """
       Ensure only superuser can edit service details
        """
        if self.request.user.is_superuser:
            return True

    def delete(self, request, *args, **kwargs):
        """
        This function is used to display sucess message given
        SucessMessageMixin cannot be used in generic.DeleteView.
        Credit: https://stackoverflow.com/questions/24822509/
        success-message-in-deleteview-not-shown
        """
        messages.success(self.request, self.success_message)
        return super(DeleteEnquiry, self).delete(request, *args, **kwargs)

contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Enquiry{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="overlay"></div>
<div class="container pb-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-left pt-5"  style="color: #f0ca698f;">Make an Enquiry</h1>
        </div>
    </div>
    <hr style="background-color: #f0ca69b5;">
    <br>
    <div class="row justify-content-center ">
        <div class="col-11 col-md-8 col-lg-6 mt-3">
            <form method="post">
                {{ contact_form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-dark border-gold rounded-0 text-gold">Submit</button>
                <a class="btn btn btn-outline-dark border-gold rounded-0 m-2 text-gold" href="{%  url 'home' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact/delete_enquiry.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Delete Enquiry{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-left pt-5" style="color: #f0ca698f;">Delete Enquiry</h1>
        </div>
    </div>
    <hr style="background-color: #f0ca69b5;">
    <br>
    <p class="text-center mt-3 text-gold">Are you sure you want to delete this Enquiry?</p>
    <div class="row justify-content-center">
        <div class="col-11 col-md-6 col-lg-4 mt-3">
            <form class="text-center" method="POST">
                {%  csrf_token  %}
                <div>
                    <button class="btn btn-outline-dark border-gold rounded-0 m-2 text-gold" type="submit">Delete</button>
                    <a class="btn btn-outline-dark border-gold rounded-0 m-2 text-gold" href="{%  url 'enquiries' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact/enquiries_dashboard.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Enquiries{% endblock %}

{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container pb-5">
  <div class="row">
    <div class="col-12">
      <h1 class="text-left pt-5" style="color: #f0ca698f;">Enquiries</h1>
    </div>
  </div>
  <hr style="background-color: #f0ca69b5;">
  <br>
  <div class="container justify-content-center">
    <table class="table enquiry-table table-borderless table-hover">
      <thead>
        <tr class="border-bottom">
          <th scope="col" class="text-gold">#</th>
          <th scope="col" class="text-gold">Name</th>
          <th scope="col" class="text-gold">Enquiry Type</th>
          <th scope="col" class="text-gold" class="d-none d-md-table-cell">Message</th>
          <th scope="col" class="text-gold">Date</th>
        </tr>
      </thead>
      <tbody>
        {% for enquiry in contact_list  %}
        <tr>
          <th scope="row" style="color: #f0ca69b9;">{{ forloop.counter }}</th>
          <td>
            <a href="{% url 'enquiry_detail' enquiry.id %}" style="color: #f0ca69b9;">{{ enquiry.name }}</a>
          </td>
          <td>
            <a href="{% url 'enquiry_detail' enquiry.id %}" style="color: #f0ca69b9;">{{ enquiry.get_enquiry_type_display }}</a>
          </td>
          <td class="d-none d-md-table-cell">
            <a href="{% url 'enquiry_detail' enquiry.id %}" style="color: #f0ca69b9;">{{ enquiry.message|truncatechars:15 }}</a>
          </td>
          <td style="color: #f0ca69b9;">{{ enquiry.date }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

contact/templates/contact/enquiry_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Enquiries{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container pb-5 text-gold">
    <div class="row">
        <div class="col-12">
            <h1 class="text-left pt-5" style="color: #f0ca698f;">Enquiry</h1>
        </div>
    </div>
    <hr style="background-color: #f0ca69b5;">
    <br>
    <div class="row justify-content-center">
        <div class="col-11 col-md-8 col-lg-6 mt-3">
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <th class=" text-gold">Name:</th>
                        <td style="color: #f0ca69b9;">{{ contact.name }}</td>
                    </tr>
                    <tr>
                        <th class=" text-gold">Email:</th>
                        <td style="color: #f0ca69b9;">{{ contact.email }}</td>
                    </tr>
                    <tr>
                        <th class=" text-gold">Enquiry Type:</th>
                        <td style="color: #f0ca69b9;">{{ contact.get_enquiry_type_display }}</td>
                    </tr>
                    <tr>
                        <th class=" text-gold">Message:</th>
                        <td style="color: #f0ca69b9;">{{ contact.message }}</td>
                    </tr>
                    <tr>
                        <th class=" text-gold">Date:</th>
                        <td style="color: #f0ca69b9;">{{ contact.date }}</td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn btn-outline-dark border-gold rounded-0 m-2 text-gold" href="{%  url 'enquiries' %}">Back</a>
            <a class="btn btn btn-outline-dark border-gold rounded-0 m-2 text-gold"
                href="{% url 'delete_enquiry' contact.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}