bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

benni_rugs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('services/', include('services.urls')),
    path('testimonials/', include('testimonials.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml/', sitemap, {"sitemaps": sitemap}, name="django.contrib.sitemaps.views.sitemap",),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Services.as_view(), name='services'),
    path('add/', views.AddService.as_view(), name='add_service'),
    path('edit/<int:pk>/', views.EditService.as_view(), name='edit_service'),
    path('delete/<int:pk>/', views.DeleteService.as_view(), name='delete_service'),
]

services/models.py
"""Services Models"""

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Service(models.Model):
    """ Model for Service """
    type = models.CharField(max_length=254)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.type

    def get_absolute_url(self):
        """Get url after superuser adds/edits service"""
        return reverse('services')

services/forms.py
from django import forms
from .models import Service
from products.widgets import CustomClearableFileInput


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-gold bg-transparent text-gold'

services/views.py
"""Service Views"""

from django.views import generic
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Service
from django.urls import reverse_lazy
from .forms import ServiceForm

class Services(generic.ListView):
    """ This view is used to display all services """
    model = Service
    template_name = 'services/services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plain_message'] = True
        return context


class AddService(
        LoginRequiredMixin, UserPassesTestMixin,
        SuccessMessageMixin, generic.CreateView):

    """This view is used to allow site owner to add a new service"""
    form_class = ServiceForm
    template_name = 'services/add_service.html'
    success_message = "%(calculated_field)s was created successfully"

    def get_success_message(self, cleaned_data):
        """
        This function overrides the get_success_message() method to add
        the service type into the success message.
        """
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.type,
        )

    def test_func(self):
        """
        ensures only superuser can add new serivces
        """
        if self.request.user.is_superuser:
            return True


class EditService(
        LoginRequiredMixin, UserPassesTestMixin,
        SuccessMessageMixin, generic.UpdateView
        ):
    """
    This view is used to allow the superuser to edit Service details
    """
    model = Service
    form_class = ServiceForm
    template_name = 'services/edit_service.html'
    success_message = "%(calculated_field)s was edited successfully"

    def test_func(self):
        """
        Ensure only superuser can edit service details
        """
        if self.request.user.is_superuser:
            return True

    def get_success_message(self, cleaned_data):
        """
        Override the get_success_message() method to add the service type
        into the success message.
        """
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.type,
        )


class DeleteService(
        LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    """
    This view is used to allow the superuser to delete a service
    """
    model = Service
    template_name = 'services/delete_service.html'
    success_message = "Service deleted successfully"
    success_url = reverse_lazy('services')

    def test_func(self):
        """
       Ensure only superuser can edit service details
        """
        if self.request.user.is_superuser:
            return True

    def delete(self, request, *args, **kwargs):
        """
        This function is used to display sucess message given
        SucessMessageMixin cannot be used in generic.DeleteView.
        Credit: https://stackoverflow.com/questions/24822509/
        success-message-in-deleteview-not-shown
        """
        messages.success(self.request, self.success_message)
        return super(DeleteService, self).delete(request, *args, **kwargs)

services/templates/services/add_service.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Add Service{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-left pt-5"  style="color: #f0ca69b9;">Add a New Service</h1>
        </div>
    </div>
    <hr style="background-color: #f0ca69b5;">
    <div class="row justify-content-center mb-3">
        <div class="col-11 col-md-8 col-lg-6 mt-3">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-outline-dark border-gold rounded-0 text-gold">Add Service</button>
                <a class="btn btn btn-outline-dark border-gold rounded-0 m-2 text-gold" href="{%  url 'services' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'services/includes/image_label_script.html' %}
{% endblock %}

services/templates/services/delete_service.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Delete Service{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-left pt-5"  style="color: #f0ca69b9;">Delete Service</h1>
        </div>
    </div>
    <hr style="background-color: #f0ca69b5;">
    <p class="text-center mt-5 text-gold">Are you sure you want to delete this Service?</p>
    <div class="row justify-content-center">
        <div class="col-11 col-md-6 col-lg-4 mt-3">
            <form class="text-center" method="POST">
                {%  csrf_token  %}
                <div>
                    <button class="btn btn-outline-dark border-gold rounded-0 m-2 text-gold" type="submit">Delete</button>
                    <a class="btn btn-outline-dark border-gold rounded-0 m-2 text-gold" href="{%  url 'services' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

services/templates/services/edit_service.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Edit Service{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-left pt-4"  style="color: #f0ca69b9;">Edit Service</h1>
        </div>
    </div>
    <hr style="background-color: #f0ca69b5;">
    <div class="row justify-content-center mb-3">
        <div class="col-11 col-md-8 col-lg-6 mt-3">
            <form method="post" action="{% url 'edit_service' service.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-outline-dark border-gold rounded-0 text-gold">Edit Service</button>
                <a class="btn btn btn-outline-dark border-gold rounded-0 m-2 text-gold" href="{%  url 'services' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'services/includes/image_label_script.html' %}
{% endblock %}

services/templates/services/services.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}| Rug Services{% endblock %}


{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="container mt-5">
            <div class="col-12">
                <h1 class="text-left pt-4" style="color: #f0ca698f;">Rug Services</h1>
            </div>
            <hr style="background-color: #f0ca69b5;">
        </div>
        {% if user.is_superuser %}
        <div class="col-12">
            <div class="pt-3 text-center">
                <a href="{% url 'add_service' %}" class="btn btn-sm gold-button py-2" aria-label="add-new-service">Add New Service</a>
            </div>
        </div>
        {% endif %}
    </div>
    <br>
    {% for service in service_list  %}
    <div class="row">
        <div class="container services-inner">
            <div class="col-12 pl-md-4">
                <div class="card my-5 border-0 bg-transparent">
                    <div class="row no-gutters">
                        <div class="col-12 col-md-5 col-lg-4">
                            {% if service.image %}
                            <img src="{{ service.image.url }}" class="service-img w-100" alt="{{ service.type }}">
                            {% else %}
                            <img src="{{ MEDIA_URL }}noimage.png" alt="{{ service.type }}" class="">
                            {% endif %}
                        </div>
                        <div class="col-12 col-md-7 col-lg-8">
                            <div class="card-body px-0 px-md-4 py-2">
                                <div>
                                    <h2 class="pt-2 pt-md-0 card-title text-left text-gold">{{ service.type }}</h2>
                                </div>
                                <div class="mb-3" style="color: #f0ca69b5; line-height: 25px;">
                                    <p>
                                        {{ service.description }}
                                    </p>
                                </div>
                                {% if request.user.is_superuser %}
                                <small class="edit-delete-btns align-bottom mb-2 d-block">
                                    <a href="{% url 'edit_service' service.id %}" class="text-gold">Edit</a><span class="text-muted"> |</span>
                                    <a href="{% url 'delete_service' service.id %}" class="text-gold">Delete</a>
                                </small>
                                {% else %}
                                <div class="align-bottom">
                                    <a href="{% url 'contact' %}" class="btn bg-transparent text-gold py-2 border-gold">Enquire Now</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="btt-button shadow-sm rounded-0 border-gold">
    <div class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up text-jet mx-auto my-auto"></i>
    </div>
</div>
{% endblock %}